import { ArrowBackOutlined, ImageOutlined } from "@mui/icons-material";
import { Alert, Box, Button, CircularProgress, Stack, Typography } from "@mui/material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import * as yup from "yup";
import { MainCard } from "../../components/base/MainCard";
import { GenericForm } from "../../components/form/GenericForm";
import type { FormField } from "../../components/form/types";
import { createReward, getAdminRewards, updateReward } from "./rewardsApi";
type FormValues = { name: string; description: string; pointCost: number; stock: number; isActive: "true" | "false"; rewardPeriod: "standard" | "annual"; image: File[] };
const fields: FormField<FormValues>[] = [{ name: "name", label: "ชื่อของรางวัล", required: true }, { name: "pointCost", label: "คะแนนที่ใช้แลก", type: "number", required: true }, { name: "description", label: "รายละเอียด", type: "textarea", required: true, fullWidth: true }, { name: "stock", label: "จำนวนคงเหลือ", type: "number", required: true }, { name: "isActive", label: "สถานะ", type: "select", required: true, options: [{ label: "เปิดให้แลก", value: "true" }, { label: "ปิดการแลก", value: "false" }] }, { name: "rewardPeriod", label: "รอบรางวัล", type: "select", required: true, options: [{ label: "รางวัลทั่วไป", value: "standard" }, { label: "รางวัลประจำปี", value: "annual" }] }, { name: "image", label: "รูปของรางวัล", type: "file", required: true, fullWidth: true }];
const makeSchema = (requireImage: boolean) => yup.object({ name: yup.string().trim().min(2).max(200).required(), description: yup.string().trim().min(2).max(2000).required(), pointCost: yup.number().integer().min(1).required(), stock: yup.number().integer().min(0).required(), isActive: yup.mixed<"true" | "false">().oneOf(["true", "false"]).required(), rewardPeriod: yup.mixed<"standard" | "annual">().oneOf(["standard", "annual"]).required(), image: requireImage ? yup.array().min(1, "กรุณาแนบรูปของรางวัล").required() : yup.array().default([]) }) as yup.ObjectSchema<FormValues>;
export function RewardCatalogFormPage() { const { id } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const rewards = useQuery({ queryKey: ["admin-rewards"], queryFn: getAdminRewards }); const editing = id && id !== "new" ? rewards.data?.find((item) => item.id === id) : undefined; const save = useMutation({ mutationFn: (values: FormValues) => { const input = { name: values.name, description: values.description, pointCost: Number(values.pointCost), stock: Number(values.stock), isActive: values.isActive === "true", rewardPeriod: values.rewardPeriod, image: values.image[0] }; return editing ? updateReward({ id: editing.id, ...input }) : createReward(input); }, onSuccess: async () => { await client.invalidateQueries({ queryKey: ["admin-rewards"] }); navigate("/rewards/manage"); } }); const defaults = useMemo<FormValues>(() => editing ? { name: editing.name, description: editing.description, pointCost: editing.pointCost, stock: editing.stock, isActive: String(editing.isActive) as "true" | "false", rewardPeriod: editing.rewardPeriod, image: [] } : { name: "", description: "", pointCost: 20, stock: 1, isActive: "true", rewardPeriod: "standard", image: [] }, [editing]); if (rewards.isLoading) return <Box sx={{ minHeight: 320, display: "grid", placeItems: "center" }}><CircularProgress /></Box>; if (id && id !== "new" && !editing) return <Alert severity="warning">ไม่พบของรางวัลที่ต้องการแก้ไข</Alert>; return <Stack spacing={3}><Box><Button startIcon={<ArrowBackOutlined />} onClick={() => navigate("/rewards/manage")} sx={{ mb: 1 }}>กลับไปรายการรางวัล</Button><Typography variant="h3">{editing ? "แก้ไขของรางวัล" : "เพิ่มของรางวัล"}</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>รูปจะเก็บในพื้นที่ส่วนตัวและแสดงผ่าน signed URL</Typography></Box>{save.isError && <Alert severity="error">ไม่สามารถบันทึกของรางวัลได้</Alert>}<MainCard title={<Typography variant="h5">ข้อมูลของรางวัล</Typography>}>{editing && <Box component="img" src={editing.imageUrl ?? undefined} alt={editing.name} sx={{ width: 180, height: 180, objectFit: "cover", borderRadius: 1.5, border: 1, borderColor: "divider", mb: 3 }} />}{!editing && <Stack direction="row" spacing={1} color="text.secondary" sx={{ mb: 2, alignItems: "center" }}><ImageOutlined /><Typography>รองรับ JPG และ PNG ขนาดไม่เกิน 3 MB</Typography></Stack>}<GenericForm<FormValues> key={editing?.id ?? "new"} fields={fields.map((field) => field.name === "image" && editing ? { ...field, required: false } : field)} schema={makeSchema(!editing)} defaultValues={defaults} columns={2} submitLabel={editing ? "บันทึกการแก้ไข" : "เพิ่มของรางวัล"} onCancel={() => navigate("/rewards/manage")} onSubmit={(values) => save.mutate(values)} isSubmitting={save.isPending} /></MainCard></Stack>; }
